#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 15 15:42:57 2020

@author: giovannyencinia
"""
import sympy as sp

x=sp.Symbol('x', real=True)
a=sp.E**(sp.I*x)
b=a.expand(complex=True)
c=(a**3).expand(complex=True).expand(trig=True)

print(c)
